const articulosVarios = [
    {
        id:1,
        nombre: "Figura Zoro",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 25000,
    },
    {
        id:2,
        nombre: "Figura Luffy",
        img: "/frontend/images/productos_all/luffy.jpg",
        descripcion: "lorem",
        precio: 20000,
    },
    {
        id:3,
        nombre: "Figura Nami",
        img: "/frontend/images/productos_all/nami.jpg",
        descripcion: "lorem",
        precio: 21000,
    },
    {
        id:4,
        nombre: "Figura Brook",
        img: "/frontend/images/productos_all/brook.jpg",
        descripcion: "lorem",
        precio: 24000,
    },
    {
        id:5,
        nombre: "Figura Chopper",
        img: "/frontend/images/productos_all/chopper.jpg",
        descripcion: "lorem",
        precio: 26000,
    },
    {
        id:6,
        nombre: "Figura Sanji",
        img: "/frontend/images/productos_all/sanji.jpg",
        descripcion: "lorem",
        precio: 23000,
    },
    {
        id:7,
        nombre: "Figura Nico Robin",
        img: "/frontend/images/productos_all/nico_robin.jpg",
        descripcion: "lorem",
        precio: 15000,
    },
    {
        id:8,
        nombre: "Figura Usopp",
        img: "/frontend/images/productos_all/usopp.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:9,
        nombre: "Figura Jimbei",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:10,
        nombre: "Figura Franky",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:11,
        nombre: "Figura Naruto Uzumaki",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:12,
        nombre: "Figura Sasuke Uchiha",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:13,
        nombre: "Figura Sakura Haruno",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:14,
        nombre: "Figura Kakashi Hatake",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:15,
        nombre: "Figura Kurenai Yūhi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:16,
        nombre: "Figura Hinata Hyūga",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:17,
        nombre: "Figura Shino Aburame",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:18,
        nombre: "Figura Kiba Inuzuka",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:19,
        nombre: "Figura Asuma Sarutobi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:20,
        nombre: "Figura Shikamaru Nara",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:21,
        nombre: "Figura Chōji Akimichi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:22,
        nombre: "Figura Ino Yamanaka",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:23,
        nombre: "Figura Might Guy",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:24,
        nombre: "Figura Rock Lee",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:25,
        nombre: "Figura Neji Hyüga",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:26,
        nombre: "Figura Ten Ten",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:27,
        nombre: "Figura Jiraiya",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:28,
        nombre: "Figura Tsunade",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:29,
        nombre: "Figura Orochimaru",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:30,
        nombre: "Figura Gara",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:31,
        nombre: "Figura Kankuro",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },
    {
        id:32,
        nombre: "Figura Temari",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
    },        
]