const articulosVarios = [
    {
        id:1,
        nombre: "Roronoa Zoro",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 25000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:2,
        nombre: "Monkey D. Luffy",
        img: "/frontend/images/productos_all/luffy.jpg",
        descripcion: "lorem",
        precio: 20000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:3,
        nombre: "Nami",
        img: "/frontend/images/productos_all/nami.jpg",
        descripcion: "lorem",
        precio: 21000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:4,
        nombre: "Brook",
        img: "/frontend/images/productos_all/brook.jpg",
        descripcion: "lorem",
        precio: 24000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:5,
        nombre: "Chopper",
        img: "/frontend/images/productos_all/chopper.jpg",
        descripcion: "lorem",
        precio: 26000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:6,
        nombre: "Vinsmoke Sanji",
        img: "/frontend/images/productos_all/sanji.jpg",
        descripcion: "lorem",
        precio: 23000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:7,
        nombre: "Nico Robin",
        img: "/frontend/images/productos_all/nico_robin.jpg",
        descripcion: "lorem",
        precio: 15000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:8,
        nombre: "Usopp",
        img: "/frontend/images/productos_all/usopp.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:9,
        nombre: "Jimbei",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:10,
        nombre: "Franky",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:11,
        nombre: "Naruto Uzumaki",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:12,
        nombre: "Sasuke Uchiha",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:13,
        nombre: "Sakura Haruno",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:14,
        nombre: "Kakashi Hatake",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:15,
        nombre: "Kurenai Yūhi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:16,
        nombre: "Hinata Hyūga",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:17,
        nombre: "Shino Aburame",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:18,
        nombre: "Kiba Inuzuka",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:19,
        nombre: "Asuma Sarutobi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:20,
        nombre: "Shikamaru Nara",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:21,
        nombre: "Chōji Akimichi",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:22,
        nombre: "Ino Yamanaka",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:23,
        nombre: "Might Guy",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:24,
        nombre: "Rock Lee",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:25,
        nombre: "Neji Hyüga",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:26,
        nombre: "Ten Ten",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:27,
        nombre: "Jiraiya",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:28,
        nombre: "Tsunade",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:29,
        nombre: "Orochimaru",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:30,
        nombre: "Gara",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:31,
        nombre: "Kankuro",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },
    {
        id:32,
        nombre: "Temari",
        img: "/frontend/images/productos_all/zoro.jpg",
        descripcion: "lorem",
        precio: 35000,
        link: "/frontend/html/productos-individuales/articulo001.html",
    },        
]